// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Co2CalculatorWebAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230925205024_InputUpdateNew1")]
    partial class InputUpdateNew1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Entities.Models.Culture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("CultureId");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cultures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Name = "Corn"
                        },
                        new
                        {
                            Id = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Name = "Wheat"
                        },
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Name = "Ray"
                        });
                });

            modelBuilder.Entity("Entities.Models.CultureInput", b =>
                {
                    b.Property<Guid>("CultureId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("InputId")
                        .HasColumnType("char(36)");

                    b.HasKey("CultureId", "InputId");

                    b.HasIndex("InputId");

                    b.ToTable("CultureInputs");
                });

            modelBuilder.Entity("Entities.Models.Input", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("InputId");

                    b.Property<decimal>("Co2EqPerKgCoefficient")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("InputTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("InputTypeId");

                    b.ToTable("Inputs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01906959-9e63-423a-8add-f6e3198ac9fa"),
                            Co2EqPerKgCoefficient = 9.78m,
                            InputTypeId = new Guid("4d80714f-8bda-4e8b-82cd-af9c5be709ec"),
                            Name = "NitrogenFertilizer"
                        },
                        new
                        {
                            Id = new Guid("ff6ac44d-5539-4a8d-add5-aa71354aca81"),
                            Co2EqPerKgCoefficient = 0.73m,
                            InputTypeId = new Guid("4d80714f-8bda-4e8b-82cd-af9c5be709ec"),
                            Name = "Urea"
                        },
                        new
                        {
                            Id = new Guid("8ab62401-e837-4bda-8c36-1b9aaf49300a"),
                            Co2EqPerKgCoefficient = 0.16m,
                            InputTypeId = new Guid("4d80714f-8bda-4e8b-82cd-af9c5be709ec"),
                            Name = "KaliumFertilizer"
                        },
                        new
                        {
                            Id = new Guid("74e865a8-1fc6-4f18-8a6f-77778ff51fb7"),
                            Co2EqPerKgCoefficient = 4.5m,
                            InputTypeId = new Guid("4d80714f-8bda-4e8b-82cd-af9c5be709ec"),
                            Name = "PhosphorusFertilizer"
                        });
                });

            modelBuilder.Entity("Entities.Models.InputType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("InputTypeId");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("InputType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c0f49a0-e74b-4542-bf93-c82bb9a2b8ff"),
                            Name = "Soil"
                        },
                        new
                        {
                            Id = new Guid("854c37b3-8ea1-4080-b569-904410bd313f"),
                            Name = "Fuel"
                        },
                        new
                        {
                            Id = new Guid("d1d73d63-c4be-4ce6-ad84-770bf620be47"),
                            Name = "Pesticide"
                        },
                        new
                        {
                            Id = new Guid("3314fe3b-6af1-43d9-a417-e4af1b221038"),
                            Name = "Fertilizer"
                        });
                });

            modelBuilder.Entity("Entities.Models.CultureInput", b =>
                {
                    b.HasOne("Entities.Models.Culture", "Culture")
                        .WithMany("CultureInputs")
                        .HasForeignKey("CultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Input", "Input")
                        .WithMany("CultureInputs")
                        .HasForeignKey("InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Culture");

                    b.Navigation("Input");
                });

            modelBuilder.Entity("Entities.Models.Input", b =>
                {
                    b.HasOne("Entities.Models.InputType", "InputType")
                        .WithMany("Inputs")
                        .HasForeignKey("InputTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InputType");
                });

            modelBuilder.Entity("Entities.Models.Culture", b =>
                {
                    b.Navigation("CultureInputs");
                });

            modelBuilder.Entity("Entities.Models.Input", b =>
                {
                    b.Navigation("CultureInputs");
                });

            modelBuilder.Entity("Entities.Models.InputType", b =>
                {
                    b.Navigation("Inputs");
                });
#pragma warning restore 612, 618
        }
    }
}
